version: '3.8'

services:
  web:
    build:
      context: .
      args:
        - NEXT_PUBLIC_TMDB_API_KEY=${NEXT_PUBLIC_TMDB_API_KEY}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_TMDB_API_KEY=${NEXT_PUBLIC_TMDB_API_KEY}
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
